server:
  port: 8200

spring:
  application:
    name: CustomerDetailsMS
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:1111
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411
  cloud:
    config:
      failFast: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/infytel_customer
    username: saulrb
    password: Srm1510Pa
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG
        type: trace

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10000
      failureRateThreshold: 6
      eventConsumerBufferSize: 1
      registerHealthIndicator: true
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsHalfOpenState: 10
  instances:
    friendFamilyMS:
      baseConfig: default
      waitDurationInOpenState: 5000
    plansMS:
      baseConfig: someShared

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    friendFamilyMS:
      baseConfig: default
    plansMS:
      baseConfig: default

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100
  instances:
    friendFamilyMS:
      maxConcurrentCalls: 10
    plansMS:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 20

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2
  instances:
    friendFamilyMS:
      baseConfig: default
    plansMS:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
  instances:
    friendFamilyMS:
      baseConfig: default
    plansMS:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: false
      timeoutDuration: 2s
  instances:
    friendFamilyMS:
      baseConfig: default
    plansMS:
      baseConfig: default